import { createClient, SupabaseClient } from '@supabase/supabase-js';
import supabaseConfigRaw from '../../supabase-config.json';

export interface SupabaseConfig {
  supabaseUrl: string;
  supabaseAnonKey: string;
}

const env = (import.meta as any).env || {};

// Read initial config from supabase-config.json, env vars, or localStorage override
const getActiveConfig = (): SupabaseConfig => {
  const localSaved = localStorage.getItem('supabase_custom_config');
  if (localSaved) {
    try {
      const parsed = JSON.parse(localSaved);
      if (parsed.supabaseUrl && parsed.supabaseAnonKey) {
        return parsed;
      }
    } catch (e) {
      console.warn("Could not parse saved Supabase config from localStorage", e);
    }
  }

  const url = supabaseConfigRaw.supabaseUrl || env.VITE_SUPABASE_URL || "";
  const key = supabaseConfigRaw.supabaseAnonKey || env.VITE_SUPABASE_ANON_KEY || "";

  return {
    supabaseUrl: url.trim(),
    supabaseAnonKey: key.trim(),
  };
};

let currentConfig = getActiveConfig();

// Initialize Supabase client
const initSupabaseClient = (cfg: SupabaseConfig): SupabaseClient | null => {
  if (!cfg.supabaseUrl || !cfg.supabaseAnonKey) {
    return null;
  }
  // Standard placeholder check
  if (
    cfg.supabaseUrl.includes('YOUR_SUPABASE') ||
    cfg.supabaseAnonKey.includes('YOUR_SUPABASE') ||
    cfg.supabaseUrl.includes('your-supabase-project')
  ) {
    return null;
  }

  try {
    // Check if CDN loaded global supabase or use imported createClient
    if (typeof window !== 'undefined' && (window as any).supabase && (window as any).supabase.createClient) {
      return (window as any).supabase.createClient(cfg.supabaseUrl, cfg.supabaseAnonKey, {
        auth: { persistSession: true }
      });
    }
    return createClient(cfg.supabaseUrl, cfg.supabaseAnonKey, {
      auth: { persistSession: true }
    });
  } catch (err) {
    console.error("Error al inicializar cliente de Supabase:", err);
    return null;
  }
};

export let supabase: SupabaseClient | null = initSupabaseClient(currentConfig);

export const isSupabaseConfigured = (): boolean => {
  if (!supabase || !currentConfig.supabaseUrl || !currentConfig.supabaseAnonKey) {
    return false;
  }
  const url = currentConfig.supabaseUrl.trim().toLowerCase();
  const key = currentConfig.supabaseAnonKey.trim().toLowerCase();
  if (!url.startsWith('http://') && !url.startsWith('https://')) {
    return false;
  }
  if (
    url.includes('your_supabase') ||
    url.includes('your-supabase') ||
    url.includes('placeholder') ||
    key.includes('your_supabase') ||
    key.includes('your-supabase') ||
    key.includes('placeholder')
  ) {
    return false;
  }
  return true;
};

export const getSupabaseConfig = () => {
  return {
    ...currentConfig,
    isConfigured: isSupabaseConfigured(),
  };
};

export const updateSupabaseConfig = (newUrl: string, newKey: string) => {
  const updated = {
    supabaseUrl: newUrl.trim(),
    supabaseAnonKey: newKey.trim()
  };
  localStorage.setItem('supabase_custom_config', JSON.stringify(updated));
  currentConfig = updated;
  supabase = initSupabaseClient(currentConfig);
  window.dispatchEvent(new Event('supabase_config_changed'));
  return isSupabaseConfigured();
};

export const resetSupabaseConfig = () => {
  localStorage.removeItem('supabase_custom_config');
  currentConfig = getActiveConfig();
  supabase = initSupabaseClient(currentConfig);
  window.dispatchEvent(new Event('supabase_config_changed'));
};

export interface ChatMessageRecord {
  id?: string | number;
  usuario_id: string;
  mensaje_usuario: string;
  respuesta_ia: string;
  created_at?: string;
}

/**
 * SQL Schema recomendado para ejecutar en la consola SQL de Supabase
 */
export const SUPABASE_SQL_SCHEMA = `-- Copia y pega este script en el SQL Editor de tu proyecto en Supabase:

CREATE TABLE IF NOT EXISTS public.app_data (
  id TEXT PRIMARY KEY,
  collection_name TEXT NOT NULL,
  doc_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  data JSONB NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla para Historial de Chats con IA
CREATE TABLE IF NOT EXISTS public.historial_chats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id TEXT NOT NULL,
  mensaje_usuario TEXT NOT NULL,
  respuesta_ia TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar tiempo real (Realtime)
ALTER PUBLICATION supabase_realtime ADD TABLE public.app_data;
ALTER PUBLICATION supabase_realtime ADD TABLE public.historial_chats;

-- Índices para búsquedas veloces
CREATE INDEX IF NOT EXISTS idx_app_data_lookup ON public.app_data(collection_name, user_id);
CREATE INDEX IF NOT EXISTS idx_historial_chats_usuario ON public.historial_chats(usuario_id);

-- Políticas RLS permisivas para la app
ALTER TABLE public.app_data ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acceso público lectura/escritura app_data" ON public.app_data
  FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.historial_chats ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acceso público lectura/escritura historial_chats" ON public.historial_chats
  FOR ALL USING (true) WITH CHECK (true);
`;

/**
 * Servicio centralizado para almacenamiento y sincronización en tiempo real con Supabase
 */
export const supabaseDbService = {
  // Guardar/Actualizar documento en Supabase
  saveDocument: async (collectionName: string, docId: string, data: any, userId: string = 'global'): Promise<boolean> => {
    if (!isSupabaseConfigured() || !supabase) return false;
    try {
      const compositeId = `${userId}_${collectionName}_${docId}`;
      const payload = {
        id: compositeId,
        collection_name: collectionName,
        doc_id: docId,
        user_id: userId,
        data: data,
        updated_at: new Date().toISOString()
      };

      const { error } = await supabase
        .from('app_data')
        .upsert(payload, { onConflict: 'id' });

      if (error) {
        console.warn(`[Supabase] No se pudo guardar en [${collectionName}]:`, error.message);
        return false;
      }
      return true;
    } catch (err: any) {
      console.warn(`[Supabase] Excepción al guardar en [${collectionName}]:`, err?.message || err);
      return false;
    }
  },

  // Obtener todos los documentos de una colección
  getCollection: async (collectionName: string, userId: string = 'global'): Promise<any[]> => {
    if (!isSupabaseConfigured() || !supabase) return [];
    try {
      const { data, error } = await supabase
        .from('app_data')
        .select('data')
        .eq('collection_name', collectionName)
        .or(`user_id.eq.${userId},user_id.eq.global`);

      if (error) {
        console.warn(`[Supabase] No se pudo consultar colección [${collectionName}]:`, error.message);
        return [];
      }

      return data ? data.map(item => item.data) : [];
    } catch (err: any) {
      console.warn(`[Supabase] Excepción al obtener colección [${collectionName}]:`, err?.message || err);
      return [];
    }
  },

  // Eliminar documento
  deleteDocument: async (collectionName: string, docId: string, userId: string = 'global'): Promise<boolean> => {
    if (!isSupabaseConfigured() || !supabase) return false;
    try {
      const compositeId = `${userId}_${collectionName}_${docId}`;
      const { error } = await supabase
        .from('app_data')
        .delete()
        .eq('id', compositeId);

      if (error) {
        console.warn(`[Supabase] No se pudo eliminar de [${collectionName}]:`, error.message);
        return false;
      }
      return true;
    } catch (err: any) {
      console.warn(`[Supabase] Excepción al eliminar de [${collectionName}]:`, err?.message || err);
      return false;
    }
  },

  // Suscribirse a cambios en tiempo real entre múltiples dispositivos
  subscribeToCollection: (
    collectionName: string, 
    userId: string = 'global', 
    onUpdate: (docs: any[]) => void
  ) => {
    if (!isSupabaseConfigured() || !supabase) return () => {};

    try {
      const uniqueId = Math.random().toString(36).substring(2, 9);
      const channelName = `realtime_${collectionName}_${userId}_${uniqueId}`;
      const channel = supabase
        .channel(channelName)
        .on(
          'postgres_changes',
          {
            event: '*',
            schema: 'public',
            table: 'app_data',
            filter: `collection_name=eq.${collectionName}`
          },
          async () => {
            try {
              const updatedDocs = await supabaseDbService.getCollection(collectionName, userId);
              onUpdate(updatedDocs);
            } catch (err) {
              console.warn("[Supabase Realtime] Error en callback de actualización:", err);
            }
          }
        );

      channel.subscribe();

      return () => {
        try {
          if (supabase && channel) {
            supabase.removeChannel(channel);
          }
        } catch (err) {
          console.warn("[Supabase Realtime] Error al remover canal:", err);
        }
      };
    } catch (err) {
      console.warn("[Supabase Realtime] Error creando canal Realtime:", err);
      return () => {};
    }
  },

  // Búsqueda pública por patente en tiempo real (para portal de clientes desde código QR)
  searchSessionByPlate: async (plateText: string): Promise<{ parking: any | null; wash: any | null }> => {
    if (!isSupabaseConfigured() || !supabase) return { parking: null, wash: null };
    const cleanPlate = plateText.trim().toUpperCase().replace(/[^A-Z0-9]/g, '');
    if (!cleanPlate) return { parking: null, wash: null };

    try {
      const { data, error } = await supabase
        .from('app_data')
        .select('data, collection_name')
        .in('collection_name', ['sessions', 'washSessions']);

      if (error || !data) return { parking: null, wash: null };

      let foundParking: any = null;
      let foundWash: any = null;

      for (const row of data) {
        const item = row.data;
        if (!item || !item.plate) continue;
        const norm = item.plate.toString().trim().toUpperCase().replace(/[^A-Z0-9]/g, '');
        if (norm === cleanPlate) {
          if (row.collection_name === 'sessions') {
            if (!foundParking || item.status === 'active') {
              foundParking = item;
            }
          } else if (row.collection_name === 'washSessions') {
            if (!foundWash || item.status !== 'entregado') {
              foundWash = item;
            }
          }
        }
      }

      return { parking: foundParking, wash: foundWash };
    } catch (err: any) {
      console.warn("[Supabase] Error buscando por patente:", err?.message || err);
      return { parking: null, wash: null };
    }
  },

  // --- HISTORIAL DE CHATS (Tabla historial_chats) ---

  // 1. Guardar mensaje de usuario y respuesta de IA en Supabase
  saveChatMessage: async (userId: string, mensajeUsuario: string, respuestaIa: string): Promise<boolean> => {
    if (!isSupabaseConfigured() || !supabase) return false;
    try {
      const uId = userId || 'global';
      const payload = {
        usuario_id: uId,
        mensaje_usuario: mensajeUsuario,
        respuesta_ia: respuestaIa,
        created_at: new Date().toISOString()
      };

      const { error } = await supabase
        .from('historial_chats')
        .insert(payload);

      if (error) {
        console.warn(`[Supabase] Error insertando en 'historial_chats':`, error.message);
        // Fallback: Si no tiene la columna created_at
        const { error: errorNoCreatedAt } = await supabase
          .from('historial_chats')
          .insert({
            usuario_id: uId,
            mensaje_usuario: mensajeUsuario,
            respuesta_ia: respuestaIa
          });

        if (errorNoCreatedAt) {
          console.warn(`[Supabase] Fallback insert error en 'historial_chats':`, errorNoCreatedAt.message);
          return false;
        }
      }
      return true;
    } catch (err: any) {
      console.warn(`[Supabase] Excepción al guardar chat:`, err?.message || err);
      return false;
    }
  },

  // 2. Obtener historial de chats para usuario_id desde la tabla historial_chats
  getChatHistory: async (userId: string): Promise<ChatMessageRecord[]> => {
    if (!isSupabaseConfigured() || !supabase) return [];
    try {
      const uId = userId || 'global';
      const { data, error } = await supabase
        .from('historial_chats')
        .select('*')
        .or(`usuario_id.eq.${uId},usuario_id.eq.global`)
        .order('id', { ascending: true });

      if (error) {
        console.warn(`[Supabase] Error consultando 'historial_chats':`, error.message);
        // Fallback sin order de 'id'
        const { data: dataFallback, error: errorFallback } = await supabase
          .from('historial_chats')
          .select('*')
          .or(`usuario_id.eq.${uId},usuario_id.eq.global`);

        if (errorFallback) {
          console.warn(`[Supabase] Fallback query error 'historial_chats':`, errorFallback.message);
          return [];
        }
        return dataFallback || [];
      }

      return data || [];
    } catch (err: any) {
      console.warn(`[Supabase] Excepción consultando 'historial_chats':`, err?.message || err);
      return [];
    }
  },

  // 3. Suscribirse en tiempo real a los chats de este usuario
  subscribeToChatHistory: (userId: string, onUpdate: (chats: ChatMessageRecord[]) => void) => {
    if (!isSupabaseConfigured() || !supabase) return () => {};

    const uId = userId || 'global';
    const channelName = `realtime:historial_chats:${uId}`;
    
    const channel = supabase
      .channel(channelName)
      .on(
        'postgres_changes',
        {
          event: '*',
          schema: 'public',
          table: 'historial_chats'
        },
        async () => {
          const updatedChats = await supabaseDbService.getChatHistory(uId);
          onUpdate(updatedChats);
        }
      )
      .subscribe();

    return () => {
      if (supabase) {
        supabase.removeChannel(channel);
      }
    };
  }
};
